### PR TITLE
improve travis

### PR DESCRIPTION
**Pull request by fserra**

### CODE REVIEW

**Comment by fserra** [comment]
ok apparently it is impossible to upgrade travis' glibc. the self extracting arxive is compiled with a very new gcc apparently and so it cannot work. Any ideas @mattmilten

**Comment by mattmilten** [comment]
It's not that I didn't try something similar and also failed miserably...

**Comment by mattmilten** [comment]
You might want to check out the test-debian branch.

https://github.com/SCIP-Interfaces/PySCIPOpt/blob/test-debian/.travis.yml

**Comment by mattmilten** [comment]
I've seen somewhere that we might need to specify the `GCC` or `CC` variables to point to the new gcc. I can't find it right now, though.

**Pull request closed without merging**
