### PR TITLE
Add scip.Model export to / import from Python pointer

### LINKED ISSUE #330: Model from/to pointer
Hello,

We're developing a [library](github.com/ds4dm/ecole) with Python bindings using Scip in the background and we would like our user to be able to leverage PyScipOpt for their own customization.

The easiest for us would be to exchange a `SCIP*` through Python, using [`ctypes.c_void_p`](https://docs.python.org/3.8/library/ctypes.html#ctypes.c_void_p).
For PyScipOpt, I would see this as adding two methods:

```python
class Model:
    ...

    @classmethod
    def from_ptr(cls, ptr: ctypes.c_void_p, take_ownership: bool) -> cls: ...

    def to_ptr(self, give_ownership:bool) -> ctypes.c_void_p: ...
```
Where ownership is about de-allocating or not.
I'd happily send a PR if you're interested 🙂

### PR DESCRIPTION
**Pull request by AntoinePrv**
Here's a working solution to resolve #330 
Turns out `uintptr_t` was the key to proper casting, while `ctypes.c_void_p` is just a wrapper around an `int`.

- [x] Add export/import functions
- [x] Document functions
- [x] Add test

### CODE REVIEW

**Comment by AntoinePrv** [comment]
Do not know why Cython doesn't allow keyword here. I tried removing all typing from the declarations, it does not change anything.
Any idea?

**Comment by mattmilten** [comment]
Hmm, strange. No idea how to fix it.

**Comment by AntoinePrv** [comment]
So this is seems to be a Cython optimization for 1 argument functions.
I added a decorator to allow keywords, see `always_allow_keywords` from
[Cython doc](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html).

**Comment by fserra** [comment]
can you add an entry to the changelog, please? Otherwise, I guess we are good to merge.

**Pull request merged**
