### PR TITLE
use correct string transformation for get- and setParam()

### PR DESCRIPTION
**Pull request by mattmilten**
In the current code, we cannot pass string or char params.

### CODE REVIEW

**Comment by fserra** [comment]
did you test it? we could add a test that just sets settings and if it doesn't crash then its good

**Comment by mattmilten** [comment]
Yeah, I tested it. But if we had test, we would have noticed the bug a lot earlier...

**Comment by mattmilten** [comment]
I'll just a add a quick test to `test_model`, ok?

**Comment by fserra** [comment]
ok

**Comment by fserra** [comment]
the build failed because of some travis stuff... do you know if one can rerun a build ?

**Comment by mattmilten** [comment]
I just triggered a new build.

**Pull request merged**
