### PR TITLE
Move main Python class definitions into scip.pxd.

### PR DESCRIPTION
**Pull request by yozw**
Doing this enables writing custom extensions (in the form of .pyx files) to PySCIPOpt.

### CODE REVIEW

**Comment by mattmilten** [comment]
Looks good to me. @fserra, what do you think?

**Comment by yozw** [comment]
Friendly ping to @fserra. We are currently blocked on this particular pull request being accepted: I have two .pyx libraries that depend on this and I'm postponing further development until I'm sure that writing custom extensions is supported. (That's by no means an attempt to pressure you into accepting this; just getting a decision would be great.)

**Comment by fserra** [comment]
hey guys
i am sorry, i am currently on vacation without much time..i had a quick look and looks good. i guess it would make sense to add an entry in the changelog and maybe something on the readme
@mattmilten i leave the rest to you

**Comment by mattmilten** [comment]
Very good point! @yozw, can you please add an entry to the CHANGELOG shortly explaining the change?

**Comment by yozw** [comment]
@fserra: Sorry! I didn't realise you were on vacation!

@mattmilten: Yes, I will add an entry. Do you mind if I do that in a separate commit, or do you want this to be a single-commit pull request?

**Comment by mattmilten** [comment]
Please just add a new commit - they're free :-)
We don't have rules about how many commits can be in a pull request and I don't see why we should.

Thanks!

**Comment by yozw** [comment]
I've added an entry to the changelog.

**Pull request merged**
