### PR TITLE
UX improvements

### PR DESCRIPTION
**Pull request by mattmilten**
Some small user experience improvements

### CODE REVIEW

**Comment by mattmilten** [comment]
Hey @fserra, any reason not to merge this?

**Comment by fserra** [comment]
Oh i didn't check the code before merging. Is it really a good idea that by default chgrhs chglhs set the bound to infinity?? If somebody calls chgrhs and doesn't provide a rhs I would expect and error, because it is most likely a bug

**Comment by mattmilten** [comment]
I did this on purpose. If you change the side and don't set one, i.e. leave it empty, you obviously don't want to set a side, hence +/- infinity. No?

**Comment by fserra** [comment]
mmm i wouldn't think so, i would imagine you forgot to set a side. I feel
that those type of this make the code much less readable. Furthermore, that
is what I'd expect from a function called, removelhs or removerhs

**Comment by mattmilten** [comment]
I see. Let's do like this: Leave the behaviour but remove the default value. So if you set a bound to `None` it will be infinity. But you always have to set one.

**Comment by fserra** [comment]
ok. i agree

**Comment by mattmilten** [comment]
This is committed in f039dd75

**Pull request merged**
